In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import plotly.express as px 
import sklearn 
import seaborn as sns

In [3]:
case_1 = pd.read_excel("case_study1.xlsx")
case_2 = pd.read_excel("case_study2.xlsx")
description = pd.read_excel("Features_Target_Description.xlsx")
unseen = pd.read_excel("Unseen_Dataset.xlsx")

In [4]:
case_1.shape, case_2.shape, description.shape, unseen.shape

((51336, 26), (51336, 62), (88, 3), (100, 42))

In [5]:
case_1 = case_1.drop_duplicates()
case_1

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [6]:
case_2 = case_2.drop_duplicates()
case_2

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,24,23,2,24,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32,-99999,-99999,0,-99999,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,others,others,681,P2

In [9]:
print(case_1.duplicated().sum()),
print(case_2.duplicated().sum())

0
0

In [7]:
case_1.isna().sum(), case_2.isna().sum()

(PROSPECTID              0
 Total_TL                0
 Tot_Closed_TL           0
 Tot_Active_TL           0
 Total_TL_opened_L6M     0
 Tot_TL_closed_L6M       0
 pct_tl_open_L6M         0
 pct_tl_closed_L6M       0
 pct_active_tl           0
 pct_closed_tl           0
 Total_TL_opened_L12M    0
 Tot_TL_closed_L12M      0
 pct_tl_open_L12M        0
 pct_tl_closed_L12M      0
 Tot_Missed_Pmnt         0
 Auto_TL                 0
 CC_TL                   0
 Consumer_TL             0
 Gold_TL                 0
 Home_TL                 0
 PL_TL                   0
 Secured_TL              0
 Unsecured_TL            0
 Other_TL                0
 Age_Oldest_TL           0
 Age_Newest_TL           0
 dtype: int64,
 PROSPECTID                      0
 time_since_recent_payment       0
 time_since_first_deliquency     0
 time_since_recent_deliquency    0
 num_times_delinquent            0
                                ..
 GL_Flag                         0
 last_prod_enq2                  0
 first_prod_enq2                 0
 Credit_Score                    0
 Approved_Flag                   0
 Length: 62, dtype: int64)

In [8]:
case_1.isna().sum().sum(), case_2.isna().sum().sum()

(np.int64(0), np.int64(0))

In [10]:
(case_2 == -99999).sum().sort_values(ascending=False)

CC_utilization                  47636
PL_utilization                  44435
max_delinquency_level           35949
time_since_first_deliquency     35949
time_since_recent_deliquency    35949
                                ...
GL_Flag                             0
last_prod_enq2                      0
first_prod_enq2                     0
Credit_Score                        0
Approved_Flag                       0
Length: 62, dtype: int64

In [11]:
case_2.columns.tolist()

['PROSPECTID',
 'time_since_recent_payment',
 'time_since_first_deliquency',
 'time_since_recent_deliquency',
 'num_times_delinquent',
 'max_delinquency_level',
 'max_recent_level_of_deliq',
 'num_deliq_6mts',
 'num_deliq_12mts',
 'num_deliq_6_12mts',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'num_times_30p_dpd',
 'num_times_60p_dpd',
 'num_std',
 'num_std_6mts',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_6mts',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_6mts',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'tot_enq',
 'CC_enq',
 'CC_enq_L6m',
 'CC_enq_L12m',
 'PL_enq',
 'PL_enq_L6m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L12m',
 'enq_L6m',
 'enq_L3m',
 'MARITALSTATUS',
 'EDUCATION',
 'AGE',
 'GENDER',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'pct_of_active_TLs_ever',
 'pct_opened_TLs_L6m_of_L12m',
 'pct_currentBal_all_TL',
 'CC_utilization',
 'CC_Flag',
 'PL_utilization',
 'PL_Flag',
 'pct_PL_enq_L6m_of_L12m',
 'pct_CC_enq_L6m_of_L12m',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'max_unsec_exposure_inPct',
 'HL_Flag',
 'GL_Flag',
 'last_prod_enq2',
 'first_prod_enq2',
 'Credit_Score',
 'Approved_Flag']

In [12]:
(case_2 == -99999).sum().sort_values(ascending=False).to_frame("Count")

                              Count
CC_utilization                47636
PL_utilization                44435
max_delinquency_level         35949
time_since_first_deliquency   35949
time_since_recent_deliquency  35949
...                             ...
GL_Flag                           0
last_prod_enq2                    0
first_prod_enq2                   0
Credit_Score                      0
Approved_Flag                     0

[62 rows x 1 columns]

In [13]:
case_2.replace(-99999, np.nan, inplace=True)

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549.0,35.0,15.0,11,29.0,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302.0,11.0,3.0,9,25.0,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,NaN,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15.0,24.0,23.0,2,24.0,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,others,others,681,P2

In [14]:
case_2.isna().sum().sort_values(ascending=False)

CC_utilization                  47636
PL_utilization                  44435
max_delinquency_level           35949
time_since_first_deliquency     35949
time_since_recent_deliquency    35949
                                ...
GL_Flag                             0
last_prod_enq2                      0
first_prod_enq2                     0
Credit_Score                        0
Approved_Flag                       0
Length: 62, dtype: int64

In [15]:
missing = (
    case_2.isna().sum()
    / len(case_2)
    * 100
).sort_values(ascending=False)

missing

CC_utilization                  92.792582
PL_utilization                  86.557192
max_delinquency_level           70.026882
time_since_first_deliquency     70.026882
time_since_recent_deliquency    70.026882
                                  ...
GL_Flag                          0.000000
last_prod_enq2                   0.000000
first_prod_enq2                  0.000000
Credit_Score                     0.000000
Approved_Flag                    0.000000
Length: 62, dtype: float64

In [16]:
pd.crosstab(
    case_2["CC_Flag"],
    case_2["CC_utilization"] == -99999
)

CC_utilization  False
CC_Flag
0               46743
1                4593

In [17]:
pd.crosstab(
    case_2["PL_Flag"],
    case_2["PL_utilization"] == -99999
)

PL_utilization  False
PL_Flag
0               42718
1                8618

In [18]:
pd.crosstab(
    case_2["num_times_delinquent"] == 0,
    case_2["time_since_first_deliquency"] == -99999
)

time_since_first_deliquency  False
num_times_delinquent
False                        15387
True                         35949

In [23]:
case_2.head(7)

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549.0,35.0,15.0,11,29.0,29,0,0,0,...,0.0,0.000,0.0,13.333,1,0,PL,PL,696,P2
1,2,47.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.000,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302.0,11.0,3.0,9,25.0,25,1,9,8,...,0.0,0.000,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,NaN,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.000,0.0,9.900,0,0,others,others,673,P2
4,5,583.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.000,0.0,NaN,0,0,AL,AL,753,P1
5,6,245.0,27.0,18.0,14,300.0,270,0,0,0,...,0.0,0.429,0.0,NaN,1,0,ConsumerLoan,PL,668,P3
6,7,49.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.000,0.0,NaN,1,0,others,others,703,P1

In [22]:
missing = (
    case_2.isna().sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

CC_utilization                  47636
PL_utilization                  44435
max_delinquency_level           35949
time_since_first_deliquency     35949
time_since_recent_deliquency    35949
max_unsec_exposure_inPct        23178
max_deliq_6mts                  12890
max_deliq_12mts                 10832
tot_enq                          6321
time_since_recent_enq            6321
CC_enq_L12m                      6321
CC_enq                           6321
PL_enq                           6321
CC_enq_L6m                       6321
PL_enq_L12m                      6321
PL_enq_L6m                       6321
enq_L12m                         6321
enq_L6m                          6321
enq_L3m                          6321
time_since_recent_payment        4291
pct_currentBal_all_TL              72
dtype: int64

In [28]:
case_2.fillna(
    {"pct_currentBal_all_TL":
     case_2["pct_currentBal_all_TL"].median()},
    inplace=True
)

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549.0,35.0,15.0,11,29.0,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302.0,11.0,3.0,9,25.0,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,NaN,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15.0,24.0,23.0,2,24.0,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74.0,NaN,NaN,0,NaN,0,0,0,0,...,0.0,0.0,0.0,NaN,0,0,others,others,681,P2

In [25]:
case_2.loc[
    case_2["time_since_recent_payment"].isna(),
    ["HL_Flag","PL_Flag","CC_Flag","GL_Flag"]
].head(20)

     HL_Flag  PL_Flag  CC_Flag  GL_Flag
3          0        0        0        0
23         0        0        0        0
40         0        0        0        0
84         0        0        0        0
85         1        0        0        0
86         0        1        0        0
102        0        0        0        1
109        0        0        0        0
119        1        0        0        0
184        1        0        0        0
191        0        0        0        0
198        0        0        0        0
201        0        0        0        0
202        1        0        0        0
214        0        0        0        0
238        0        0        0        0
251        0        0        0        0
278        1        0        0        0
289        0        0        0        0
292        0        0        0        0

In [26]:
case_2.loc[
    case_2["tot_enq"].isna(),
    ["last_prod_enq2","first_prod_enq2","tot_enq"]
].head(20)

    last_prod_enq2 first_prod_enq2  tot_enq
3           others          others      NaN
6           others          others      NaN
9           others          others      NaN
11          others          others      NaN
17          others          others      NaN
18          others          others      NaN
23          others          others      NaN
25          others          others      NaN
40          others          others      NaN
42          others          others      NaN
56          others          others      NaN
73          others          others      NaN
95          others          others      NaN
101         others          others      NaN
107         others          others      NaN
115         others          others      NaN
120         others          others      NaN
126         others          others      NaN
136         others          others      NaN
141         others          others      NaN

In [27]:
case_2.loc[
    case_2["max_unsec_exposure_inPct"].isna(),
    ["HL_Flag","PL_Flag","CC_Flag","GL_Flag"]
].head(20)

    HL_Flag  PL_Flag  CC_Flag  GL_Flag
4         0        0        0        0
5         1        0        0        0
6         1        0        0        0
7         0        0        0        0
8         0        0        0        0
11        0        0        0        0
12        0        0        0        0
14        0        0        0        0
18        0        0        0        0
22        0        0        0        0
23        0        0        0        0
25        0        0        0        1
26        0        0        1        0
27        1        0        0        0
28        1        0        0        1
35        0        0        0        0
37        1        0        0        0
38        0        0        0        0
39        0        1        0        0
40        0        0        0        0

In [31]:
pd.set_option("display.max_rows", None)
missing = case_2.isna().sum().sort_values(ascending=False)

display(missing.to_frame("Missing Values"))

                              Missing Values
CC_utilization                         47636
PL_utilization                         44435
max_delinquency_level                  35949
time_since_first_deliquency            35949
time_since_recent_deliquency           35949
max_unsec_exposure_inPct               23178
max_deliq_6mts                         12890
max_deliq_12mts                        10832
tot_enq                                 6321
time_since_recent_enq                   6321
CC_enq_L12m                             6321
CC_enq                                  6321
PL_enq                                  6321
CC_enq_L6m                              6321
PL_enq_L12m                             6321
PL_enq_L6m                              6321
enq_L12m                                6321
enq_L6m                                 6321
enq_L3m                                 6321
time_since_recent_payment               4291
num_sub_6mts                               0
num_std                                    0
num_times_60p_dpd                          0
num_times_30p_dpd                          0
num_deliq_12mts                            0
num_times_delinquent                       0
num_deliq_6_12mts                          0
PROSPECTID                                 0
max_recent_level_of_deliq                  0
num_deliq_6mts                             0
recent_level_of_deliq                      0
num_lss                                    0
num_lss_6mts                               0
num_lss_12mts                              0
num_dbt_12mts                              0
num_sub_12mts                              0
num_dbt                                    0
num_dbt_6mts                               0
num_sub                                    0
num_std_12mts                              0
num_std_6mts                               0
MARITALSTATUS                              0
NETMONTHLYINCOME                           0
EDUCATION                                  0
AGE                                        0
GENDER                                     0
pct_opened_TLs_L6m_of_L12m                 0
pct_of_active_TLs_ever                     0
Time_With_Curr_Empr                        0
pct_currentBal_all_TL                      0
PL_Flag                                    0
pct_PL_enq_L6m_of_L12m                     0
pct_CC_enq_L6m_of_L12m                     0
CC_Flag                                    0
pct_PL_enq_L6m_of_ever                     0
pct_CC_enq_L6m_of_ever                     0
HL_Flag                                    0
GL_Flag                                    0
last_prod_enq2                             0
first_prod_enq2                            0
Credit_Score                               0
Approved_Flag                              0

In [ ]:
# ☠️Data Cleaning Summary ☠️
# ✅ No duplicate rows found.
# ✅ No standard missing values (NaN) initially.
# ✅ -99999 represented missing/not applicable values and was replaced with NaN.
# ✅ Investigated missing values instead of blindly imputing them.
# ✅ pct_currentBal_all_TL had only 72 missing values (≈0.14%), so these were imputed using the median because the proportion was negligible.
# ✅ High-missing columns (CC_utilization, PL_utilization, time_since_first_delinquency, time_since_recent_delinquency, tot_enq, max_unsec_exposure_inPct, etc.) 
# were found to represent business-rule missing values (structural missingness) rather than data quality issues. These values indicate 
# situations such as no credit card, no personal loan, no delinquency history, or no credit enquiries, so they were retained as NaN.